//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJECTINVOICE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOICE
    {
        public int idinvoice { get; set; }
        public int invoice_number { get; set; }
        public Nullable<int> itype { get; set; }
        public Nullable<int> property { get; set; }
        public Nullable<int> company { get; set; }
        public Nullable<int> cost { get; set; }
        public string istatus { get; set; }
        public string idate { get; set; }
    
        public virtual Company Company1 { get; set; }
        public virtual CostType CostType { get; set; }
        public virtual Property Property1 { get; set; }
    }
}
